apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bini-service
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: bini
      component: service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
