services:
  prometheus_service:
    image: prom/prometheus:latest
    ports:
      - target: 9090
        published: 9090
        mode: ingress
    volumes:
      - ./ops/monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - monitoring-network

  grafana_service:
    image: grafana/grafana:latest
    ports:
      - target: 3000
        published: 3001
        mode: ingress
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./ops/monitoring/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml:ro
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - monitoring-network
    depends_on:
      - prometheus_service

  loki_service:
    image: grafana/loki:latest
    ports:
      - target: 3100
        published: 3100
        mode: ingress
    networks:
      - monitoring-network

networks:
  monitoring-network:
    external: true
    driver: overlay


volumes:
  prometheus-data:
  grafana-data:
  loki-data:
